In [5]:
import igl
import scipy as sp
import numpy as np
from meshplot import plot, subplot, interact
import os
import polyscope as ps
root_folder = os.getcwd()

v, f = igl.read_triangle_mesh(os.path.join(root_folder, "data", "decimated-knight.off"))
v2, f2 = igl.read_triangle_mesh(os.path.join(root_folder, "data", "knight2.obj"))
v3, f3 = igl.read_triangle_mesh(os.path.join(root_folder, "data", "knight3.obj"))


ps.init()
mesh = ps.register_surface_mesh('original',v,f)
mesh = ps.register_surface_mesh('t02',v3,f3)
mesh = ps.register_surface_mesh('t01',v2,f2)

points = ps.register_point_cloud('pointsv', v)
ints = ps.register_point_cloud('pointsv1', v1)
ints = ps.register_point_cloud('pointsv2', v2)
ints = ps.register_point_cloud('pointsv3', v3)
ps.show()

In [74]:
v, f = igl.read_triangle_mesh(os.path.join(root_folder, "data", "knight_example1copy2.obj"))
print(f)
print(len(f))

[[ 15 344  15]
 [210 313 243]
 [424 375  79]
 ...
 [175  30 211]
 [424  24  61]
 [104 130  35]]
1000


In [81]:
print("Before: ", len(f))
count = 0
i = 0
while i < len(f):#while i < len(f):
   if f[i][0]==f[i][1] and f[i][1]==f[i][2]:  
    f = np.delete(f,i,0)
    #print(f[i])
    i -= 1
    count += 1
   # j = 0
   # while j < len(f):
   #     if i != j and f[i][0]==f[j][0] and f[i][1]==f[j][1] and f[i][2]==f[j][2]:
   #         f = np.delete(f,j,0)
   #         j -= 1
            #print(f[i], f[j])
   #         count += 1
   #     j += 1
   i += 1
print(count)
print("After: ", len(f))

Before:  864
42
After:  822


In [57]:
v_ = []
for i in range(0,len(v)):
    v_.append(0)
    
for i in range(0,len(v)):
    for j in range(len(f)):
        if f[j][0] == i or  f[j][1] == i or  f[j][2] == i:
            v_[i] = 1

i = 0
count = 0
while i < len(v):
    if v_[i] == 0:
        v = np.delete(v,i,0)
        v_ = np.delete(v_,i,0)
        count += 1
    i += 1
print(count)


152


In [89]:
v, f = igl.read_triangle_mesh(os.path.join(root_folder, "data", "knight2.obj"))

v_ = []
for i in range(0,len(v)):
    v_.append(0)
    
for i in range(0,len(v)):
    for j in range(len(f)):
        if f[j][0] == i or  f[j][1] == i or  f[j][2] == i:
            v_[i] = 1
i = 0
count = 0
while i < len(v):
    if v_[i] == 0:
        v = np.delete(v,i,0)
        v_ = np.delete(v_,i,0)
        for i_ in range(0, len(f)):
                if f[i_][0]  > i:
                    f[i_][0] -= 1
                if f[i_][1]  > i:
                    f[i_][1] -= 1
                if f[i_][2]  > i:
                    f[i_][2] -= 1
        i -= 1
        count += 1
    i += 1     
print(count)
plot(v, f)
#ret = igl.write_triangle_mesh(os.path.join(root_folder, "data", "knight3.obj"), v, f)   

260


Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.4996534…

In [90]:
ret = igl.write_triangle_mesh(os.path.join(root_folder, "data", "knight2.obj"), v, f)   

In [79]:
ret = igl.write_triangle_mesh(os.path.join(root_folder, "data", "knight2.obj"), v, f)   

In [ ]:
import igl
import scipy as sp
import numpy as np
from meshplot import plot, subplot, interact
import os
import polyscope as ps
root_folder = os.getcwd()

v, f = igl.read_triangle_mesh(os.path.join(root_folder, "data", "decimated-knight.off"))

ps.init()
mesh = ps.register_surface_mesh('original',v,f)
points = ps.register_point_cloud('pointsv', v)
ps.show()